version: '3.8'

services:
  cronog-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meu-cronog-server
    volumes:
      - ./server.crt:/app/server.crt
      - ./server.key:/app/server.key
    ports:
      - "5001:5001"
    restart: always
    environment:
      - PORT=5001
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID}
      - FIREBASE_DB_TYPE=${FIREBASE_DB_TYPE}
      - FIREBASE_DB_PRIVATE_KEY_ID=${FIREBASE_DB_PRIVATE_KEY_ID}
      - FIREBASE_DB_PRIVATE_KEY=${FIREBASE_DB_PRIVATE_KEY}
      - FIREBASE_DB_CLIENT_EMAIL=${FIREBASE_DB_CLIENT_EMAIL}
      - FIREBASE_DB_CLIENT_ID=${FIREBASE_DB_CLIENT_ID}
      - FIREBASE_DB_AUTH_URI=${FIREBASE_DB_AUTH_URI}
      - FIREBASE_DB_TOKEN_URI=${FIREBASE_DB_TOKEN_URI}
      - FIREBASE_DB_AUTH_PROVIDER_X509_C=${FIREBASE_DB_AUTH_PROVIDER_X509_C}
      - FIREBASE_DB_CLIENT_X509_CERT_URL=${FIREBASE_DB_CLIENT_X509_CERT_URL}
      - FIREBASE_DB_UNIVERSE_DOMAIN=${FIREBASE_DB_UNIVERSE_DOMAIN}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}