version: '3.8'

services:
  cronog-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cronog-server
    ports:
      - "5001:5001"
    restart: always
    env_file:
      - .env